# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-19 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20161112_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='A postagem será exibida somente após essa data.', verbose_name='Publicação'),
        ),
    ]
