# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-29 18:53
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sobre', '0002_auto_20161015_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sobre',
            options={'verbose_name': 'Sobre', 'verbose_name_plural': 'Sobre'},
        ),
        migrations.AlterField(
            model_name='sobre',
            name='descricao',
            field=redactor.fields.RedactorField(verbose_name='Descrição'),
        ),
    ]
